### ISSUE TITLE
UnicodeEncodeError character encoding error

### ISSUE THREAD

**Issue by lulukas86** [tschinz/maloney_streamfetcher#1]
Hi tschinz
Running the script on Mac OSX 10.12.5 gives the following error.

```
python maloney_streamfetcher.py -l -v
No ID given, will download all available episodes from the mainpage
Traceback (most recent call last):
  File "maloney_streamfetcher.py", line 201, in <module>
    maloney_downloader.fetch_latest(outdir = args.outdir, uid=args.uid)
  File "maloney_streamfetcher.py", line 30, in fetch_latest
    self.process_maloney_episodes(srf_maloney_url, outdir=outdir, uid=uid)
  File "maloney_streamfetcher.py", line 64, in process_maloney_episodes
    uids = self.parse_html(page)
  File "maloney_streamfetcher.py", line 133, in parse_html
    lines = str(page).split("\n")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 1813: ordinal not in range(128)
```

Python version 2.7.10. Any idea what the issue could be?

Thanks
Lukas

**Comment by lulukas86** [comment]
Same on Ubuntu 17.04 with Python 2.7.13. Works on both systems with python3.

**Comment by tschinz** [comment]
Hi luke, 
well then the problem seems to be resolved? I anyway only tested it for py3. I said that it "should" be compatible for py2 but there was no guarantee.
This is a problem of using str() indead of .encode('utf-8').

You need to run it in py2?
Cheers

**Comment by lulukas86** [comment]
Yes, I will set it to resolved. It may makes sense if you delete your comment about Python 2 from the README.md
> but should be compatible with Python 2.x

With Python 3 it works like a charm. Many thanks for this cool script!

**Comment by tschinz** [comment]
see commit 8ba7962e821ab1fd71ed0d532d27440c264b385d.
Great the script was useful you. Py2 compatiblity would be simple but for this tool it's fine ;-). I don't want to spent more time on it than necessary.
Cheers
